hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}

parameters:
  layers: [6,12,24,16]
  epochs: 200
  batch_size: 128
  verbose_step: 100
  verbose: True
  momentum: 0.9
  lr: 0.1
  lr_step: 80
  lr_gamma: 0.1
  weight_decay: 0.0001
  log_dir: "./tboard"
  ckpts_dir: "./ckpts"
  num_classes: 10
  model: "densenet121"
  dataset: "cifar10"
