hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}

parameters:
  layers: [1,1,1,1]
  epochs: 200
  batch_size: 128
  verbose_step: 100
  verbose: 1
  momentum: 0.9
  lr: 0.1
  mode: "train"
  log_dir: "./tboard"
  ckpts_dir: "./ckpts"
  num_classes: 10
  model: "densenet121"
